ENV["MATCH_PASSWORD"] = 'Xamarin4ILM'
ENV["FASTLANE_PASSWORD"] = 'Xamarin4ILM'

def build_app_adhoc

    match(
        git_url: "git@github.com:ILMServices/CodeSigning.git",
        app_identifier: "com.ilmservice.vitko.test", 
        username: 'appdev@ilmservice.com',
        type:"adhoc")
  
end

def build_app_appstore

    match(
        git_url: "git@github.com:ILMServices/CodeSigning.git",
        app_identifier: "com.ilmservice.vitko.test", 
        username: 'appdev@ilmservice.com',
        type:"appstore")
    
  #Go to the Xamarin Studio command line and build the SLN
  sh 'xbuild /p:Configuration=AppStore /p:Platform=iPhone "../ilm.eventmobileapp/ilm.eventmobileapp.sln"'
  
  #TODO: We should have a real build send it up to TestFlight via pilot
  
  
end

#lane :dev do
#   build_app_dev
#end

platform :ios do
    lane :adhoc do
        build_app_adhoc
    end

    #lane :appstore do
    #    build_app_appstore
    #end
end